#!/usr/bin/env python3
"""
Hindi IPTV Validator Demo - Filters Hindi channels without actual stream validation
"""

import json
from hindi_validator import parse_m3u_metadata, load_channel_metadata, enhance_channel_metadata, filter_hindi_channels, filter_channels, is_hindi_channel

def validate_hindi_playlist_demo(input_file, output_file, metadata_file=None, country=None, category=None, output_format="m3u"):
    """Validate and filter Hindi IPTV playlist (demo version without actual stream testing)"""
    
    print("🇮🇳 Hindi IPTV Channel Validator (Demo Mode)")
    print("=" * 50)
    
    # Parse channels from M3U
    print("📋 Parsing M3U file...")
    channels = parse_m3u_metadata(input_file)
    print(f"   Found {len(channels)} total channels")
    
    # Load and enhance metadata
    if metadata_file:
        print("📝 Loading metadata...")
        metadata_config = load_channel_metadata(metadata_file)
        channels = enhance_channel_metadata(channels, metadata_config)
        print("   Metadata enhanced successfully")
    
    # Filter for Hindi channels first
    print("🔍 Filtering for Hindi channels...")
    hindi_channels = filter_hindi_channels(channels)
    print(f"   Found {len(hindi_channels)} Hindi channels")
    
    # Additional filtering if specified
    if country or category:
        print(f"🎯 Applying filters: {country or 'All countries'}, {category or 'All categories'}")
        hindi_channels = filter_channels(hindi_channels, country, category)
        print(f"   After filtering: {len(hindi_channels)} channels")
    
    if not hindi_channels:
        print("❌ No Hindi channels found matching the criteria")
        return {}
    
    # Show channel breakdown by category
    print("\n📊 Channel Breakdown:")
    category_count = {}
    for url, info in hindi_channels.items():
        cat = info.get('category', 'Unknown')
        category_count[cat] = category_count.get(cat, 0) + 1
    
    for category, count in sorted(category_count.items()):
        print(f"   {category}: {count} channels")
    
    # Demo: Simulate removing some "dead" channels (randomly for demo)
    import random
    total_channels = len(hindi_channels)
    # Simulate 70% success rate
    working_count = int(total_channels * 0.7)
    working_channels = dict(list(hindi_channels.items())[:working_count])
    dead_count = total_channels - working_count
    
    print(f"\n🔧 Stream Validation (Simulated):")
    print(f"   ✅ Working Hindi channels: {len(working_channels)}")
    print(f"   ❌ Dead channels removed: {dead_count}")
    print(f"   🚫 Blocked channels removed: 0")
    
    # Output results
    if output_format == "json":
        with open(output_file, "w", encoding='utf-8') as f:
            json.dump(working_channels, f, indent=2, ensure_ascii=False)
    else:
        # M3U format
        with open(output_file, "w", encoding='utf-8') as f:
            f.write("#EXTM3U\n")
            f.write("#EXT-X-VERSION:3\n")
            f.write("# Playlist: Hindi IPTV Channels\n")
            f.write("# Generated by Hindi IPTV Validator\n\n")
            for url, info in working_channels.items():
                title = f"{info['title']} [{info['country']}] [{info['category']}] [Hindi]"
                f.write(f"#EXTINF:-1,{title}\n")
                f.write(f"{url}\n")
    
    print(f"\n💾 Saved {len(working_channels)} working Hindi channels to {output_file}")
    
    # Show sample channels
    print(f"\n📺 Sample Working Channels:")
    for i, (url, info) in enumerate(list(working_channels.items())[:5]):
        print(f"   {i+1}. {info['title']} [{info['country']}] [{info['category']}]")
    
    return working_channels

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Hindi IPTV Playlist Validator (Demo)")
    parser.add_argument("input_file", help="Input M3U file")
    parser.add_argument("output_file", help="Output file")
    parser.add_argument("--metadata", help="Channel metadata YAML file", default="channels.yml")
    parser.add_argument("--country", help="Filter by country (default: IN for India)")
    parser.add_argument("--category", help="Filter by category (News, Sports, Entertainment, etc.)")
    parser.add_argument("--format", choices=["m3u", "json"], default="m3u", help="Output format")
    
    args = parser.parse_args()
    
    # Default to India if no country specified
    if not args.country:
        args.country = "IN"
    
    validate_hindi_playlist_demo(
        args.input_file,
        args.output_file,
        metadata_file=args.metadata,
        country=args.country,
        category=args.category,
        output_format=args.format
    )
